export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  //Composition Builder
  RESET: 'RESET',
  SELECT_PRIMARY_FLAVOR: 'SELECT_PRIMARY_FLAVOR',
  SELECT_KEYSTONE: 'SELECT_KEYSTONE',
  SELECT_PRIMARY_T1: 'SELECT_PRIMARY_T1',
  SELECT_PRIMARY_T2: 'SELECT_PRIMARY_T2',
  SELECT_PRIMARY_T3: 'SELECT_PRIMARY_T3',
  SELECT_SECONDARY_FLAVOR: 'SELECT_SECONDARY_FLAVOR',
  SELECT_SECONDARY_T1: 'SELECT_SECONDARY_T1',
  SELECT_SECONDARY_T2: 'SELECT_SECONDARY_T2',
}
