export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  //Composition Builder
  RESET: 'RESET',
  SELECT_PRIMARY_FLAVOR: 'SELECT_PRIMARY_FLAVOR',
  SELECT_KEYSTONE: 'SELECT_KEYSTONE',
  SELECT_PRIMARY_T1: 'SELECT_PRIMARY_T1',
  SELECT_PRIMARY_T2: 'SELECT_PRIMARY_T2',
  SELECT_PRIMARY_T3: 'SELECT_PRIMARY_T3',
  SELECT_SECONDARY_FLAVOR: 'SELECT_SECONDARY_FLAVOR',
  SELECT_SECONDARY_RUNES: 'SELECT_SECONDARY_RUNES',
  TOGGLE_MENU: 'TOGGLE_MENU',
  TOGGLE_INFO_DISPLAY: 'TOGGLE_INFO_DISPLAY',
}
